;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        align-cljlet
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        clipboard-kill-region
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        cua-scroll-up
        erl-openparen
        erlang-electric-comma
        erlang-electric-gt
        erlang-electric-lt
        erlang-electric-semicolon
        haskell-indentation-delete-char
        haskell-mode-contextual-space
        haskell-newline-and-indent
        ido-hacks-execute-extended-command
        isearch-backward-regexp
        isearch-forward-regexp
        isearch-other-control-char
        live-paredit-forward-kill-sexp
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-return
        org-self-insert-command
        paredit-backslash
        paredit-close-square
        paredit-doublequote
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        reindent-then-newline-and-indent
        sgml-slash
        win-switch-exit-and-redo
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        align-regexp
        isearch-delete-char
        isearch-printing-char
        win-switch-dispatch
        ))
