;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        align-cljlet
        clipboard-kill-region
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        cua-scroll-up
        erl-openparen
        erlang-electric-comma
        erlang-electric-gt
        erlang-electric-lt
        erlang-electric-semicolon
        ido-hacks-execute-extended-command
        isearch-forward-regexp
        live-paredit-forward-kill-sexp
        org-beginning-of-line
        org-return
        org-self-insert-command
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-curly
        paredit-open-round
        reindent-then-newline-and-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-printing-char
        win-switch-dispatch
        ))
